---
title: "p8105_hw6_gw2383"
author: "Guojing Wu"
date: "11/23/2018"
# output: html_document
output:
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = F, 
                      warning = F)
library(tidyverse)
theme_set(theme_bw())
```

## Problem 1

### Tidy data

```{r}
homi_df = 
  read.csv("./data/problem1/homicide-data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(city_state = paste(city, state, sep = ", "), 
         solved = ifelse(disposition == "Closed by arrest", 1, 0), # a binary indicator
         victim_race = ifelse(victim_race == "White", "White", "Nonwhite"), 
         victim_race = factor(victim_race, levels = c("White", "Nonwhite")), # a white / non white indicator
         victim_age = as.numeric(victim_age)) %>% 
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"))) # filter cities
```

### a logistic regression

```{r}
# first fit it
fit_logistic =
  homi_df %>% 
  glm(solved ~ victim_age + victim_sex + victim_race, data = ., family = binomial())

# then compute the odds ratio
fit_logistic %>% 
  broom::tidy(conf.int = T) %>% 
  mutate(OR = exp(estimate), 
         conf.low = exp(conf.low), 
         conf.high = exp(conf.high)) %>% 
  select(term, OR, conf.low, conf.high, p.value) %>% 
  filter(term %in% c("(Intercept)", "victim_raceNonwhite")) %>% 
  knitr::kable()
```

### run `glm` for each of the cities

```{r}
nest_glm_res = 
  homi_df %>% 
  group_by(city_state) %>% 
  nest() %>% 
  mutate(models = map(data, ~glm(solved ~ victim_race + victim_age + victim_sex, data = .x, family = binomial())), 
         models_esti = map(models, broom::tidy), # tidying for estimate
         models_conf = map(models, broom::confint_tidy)) %>% # tyding for conf.int
  select(-data, -models) %>%
  unnest() %>% 
  filter(term %in% c("(Intercept)", "victim_raceNonwhite")) %>% 
  mutate(OR = exp(estimate), 
         conf.low = exp(conf.low), 
         conf.high = exp(conf.high)) %>% 
  select(city_state, term, OR, conf.low, conf.high, p.value)

nest_glm_res
```

Then create a plot that shows the estimated ORs and CIs for each city, and comment on the plot.

```{r, dpi = 300}
nest_glm_res %>% 
  filter(term == "victim_raceNonwhite") %>% 
  ggplot(aes(x = reorder(city_state, OR), y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  labs(x = "city", 
       y = "ORs and CIs for nonwhite victims comparing to white victims") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```


